// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTSP9SKcMCOIzcVIhPrJPQGI_1BlpYXy4',
    appId: '1:107125014939:web:6f94a3703263903e65a13e',
    messagingSenderId: '107125014939',
    projectId: 'smarthostel-c72d0',
    authDomain: 'smarthostel-c72d0.firebaseapp.com',
    storageBucket: 'smarthostel-c72d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDmrequlL78fFiYog7cqVeaubntcgCGvY',
    appId: '1:107125014939:android:d6deede6a76eedf165a13e',
    messagingSenderId: '107125014939',
    projectId: 'smarthostel-c72d0',
    storageBucket: 'smarthostel-c72d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRPClQWZk58LoIuX145jKCvNAKf4L7AjE',
    appId: '1:107125014939:ios:5555967d85d3f71b65a13e',
    messagingSenderId: '107125014939',
    projectId: 'smarthostel-c72d0',
    storageBucket: 'smarthostel-c72d0.firebasestorage.app',
    iosBundleId: 'com.example.hostelAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRPClQWZk58LoIuX145jKCvNAKf4L7AjE',
    appId: '1:107125014939:ios:5555967d85d3f71b65a13e',
    messagingSenderId: '107125014939',
    projectId: 'smarthostel-c72d0',
    storageBucket: 'smarthostel-c72d0.firebasestorage.app',
    iosBundleId: 'com.example.hostelAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTSP9SKcMCOIzcVIhPrJPQGI_1BlpYXy4',
    appId: '1:107125014939:web:c0f5ed9420f70e3465a13e',
    messagingSenderId: '107125014939',
    projectId: 'smarthostel-c72d0',
    authDomain: 'smarthostel-c72d0.firebaseapp.com',
    storageBucket: 'smarthostel-c72d0.firebasestorage.app',
  );
}
